### ISSUE TITLE
Package removed from AUR

### ISSUE THREAD

**Issue by NormalRa** [denysvitali/aur-firefox-dev-automaintainer#1]
Is it just me or has this package been deleted **twice** now from the AUR?

**Comment by denysvitali** [comment]
Yes, apparently @eli-schwartz complained about it and they got it removed.
https://lists.archlinux.org/pipermail/aur-requests/2017-February/015707.html

Then, a couple of hours later a new build was released, so the autimated script pushed the changes, and because a package in AUR is created when a repo is pushed, it was created again. Then @eli-schwartz complained again and got it removed for the second time.

Apparently we can't have an auto-updating Firefox Dev build on the AUR, and the firefox-developer doesn't update his package, nor accepts suggestions from the comments.

To be honest I thought that the AUR mods could have handled the case better, since they complained about duplicated packages (firefox-dev, firefox-developer, firefox-aurora) but only deleted mine.  
Plus, apparently the 10 versions of firefox-developer- are perfectly okay for them.  
  
Sorry about that, apparently AUR doesn't want this package

**Comment by NormalRa** [comment]
> Then, a couple of hours later a new build was released, so the autimated script pushed the changes, and because a package in AUR is created when a repo is pushed, it was created again. Then @eli-schwartz complained again and got it removed for the second time.

Thank you for the explanation, I was having a wtf-is-going-on/déjà-vu moment :D

> Apparently we can't have an auto-updating Firefox Dev build on the AUR, and the firefox-developer doesn't update his package, nor accepts suggestions from the comments.

That's unfortunate. It was pretty frustrating not being able to trust the current state of affairs surrounding nightly firefox packages. First `firefox-aurora`, then `firefox-developer`, and now `firefox-dev`. The politics do not interest me, so an auto-updating package seemed like a good idea.

> Plus, apparently the 10 versions of firefox-developer- are perfectly okay for them.

The whole thing is a mess. Hopefully it will be resolved sooner rather than later, and with an elegant solution.

> Sorry about that, apparently AUR doesn't want this package

Thank you for the effort you've put in.

**Comment by denysvitali** [comment]
I'm really sorry about this whole situation  
I don't care who is going to maintain such a package, the only thing I want (and I wanted since the beginning of this project) was to have a Firefox-Dev build that was always up to date

**Comment by eli-schwartz** [comment]
FWIW, my actual complaint was here: https://lists.archlinux.org/pipermail/aur-requests/2017-February/015702.html
And my main problem was the fact that this package showed a lack of good faith; it was essentially a ragefork. Rageforks are not permitted in the AUR, auto-updating packages are perfectly okay (in fact, this is what VCS packages are).

As for the so-called duplicate firefox-developer-* packages, those are Mozilla's independent locale-specific binary builds, so they aren't even slightly comparable. ;)
